/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as PostsCreateRouteImport } from './routes/posts/create'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountHomeRouteImport } from './routes/account/home'
import { Route as PostsPostIdDetailsRouteImport } from './routes/posts/$postId.details'

const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const PostsCreateRoute = PostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountHomeRoute = AccountHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AccountRouteRoute,
} as any)
const PostsPostIdDetailsRoute = PostsPostIdDetailsRouteImport.update({
  id: '/posts/$postId/details',
  path: '/posts/$postId/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/account/home': typeof AccountHomeRoute
  '/account/register': typeof AccountRegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/account/': typeof AccountIndexRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId/details': typeof PostsPostIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/home': typeof AccountHomeRoute
  '/account/register': typeof AccountRegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/account': typeof AccountIndexRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId/details': typeof PostsPostIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/account/home': typeof AccountHomeRoute
  '/account/register': typeof AccountRegisterRoute
  '/posts/create': typeof PostsCreateRoute
  '/account/': typeof AccountIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/details': typeof PostsPostIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/account/home'
    | '/account/register'
    | '/posts/create'
    | '/account/'
    | '/posts'
    | '/posts/$postId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/home'
    | '/account/register'
    | '/posts/create'
    | '/account'
    | '/posts'
    | '/posts/$postId/details'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/account/home'
    | '/account/register'
    | '/posts/create'
    | '/account/'
    | '/posts/'
    | '/posts/$postId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  PostsCreateRoute: typeof PostsCreateRoute
  PostsIndexRoute: typeof PostsIndexRoute
  PostsPostIdDetailsRoute: typeof PostsPostIdDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/posts/create': {
      id: '/posts/create'
      path: '/posts/create'
      fullPath: '/posts/create'
      preLoaderRoute: typeof PostsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/home': {
      id: '/account/home'
      path: '/home'
      fullPath: '/account/home'
      preLoaderRoute: typeof AccountHomeRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/posts/$postId/details': {
      id: '/posts/$postId/details'
      path: '/posts/$postId/details'
      fullPath: '/posts/$postId/details'
      preLoaderRoute: typeof PostsPostIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountHomeRoute: typeof AccountHomeRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountHomeRoute: AccountHomeRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  PostsCreateRoute: PostsCreateRoute,
  PostsIndexRoute: PostsIndexRoute,
  PostsPostIdDetailsRoute: PostsPostIdDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
